import { Anek_Devanagari } from "next/font/google";
import "./globals.css";
import ClientProvider from "../components/ClientProvider"; // Import your Client Component

const inter = Anek_Devanagari({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <main className="">{children}</main>
        </ClientProvider>
      </body>
    </html>
  );
}
